variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_TMPFS: "1G"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_W: "30"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

before_script:
  - source ~/ci-admin/env/init.sh
  - export PIPELINE_SUBDIR=${ECCI_BUILD_DIR}/precaution/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}

#----- rhel-9-amd64_gnu-11.4.1
build:rhel-9-amd64_gnu-11.4.1:
  stage: build
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ./.initial_setup
    - set -e
    - make cmake
    - make -j `nproc`

#----- rhel-9-graniterapids-64-intel-2025.1.0
build:rhel-9-graniterapids-64-intel-2025.1.0:
  stage: build
  script:
    - set +e
    - . ./.eccc_setup_intel
    - . ./.initial_setup
    - set -e
    - make cmake
    - make -j `nproc`
