variables:
  ORD_SOUMET_SHELL: "/bin/bash"
  ORD_SOUMET_CPUS: "80"
  ORD_SOUMET_TMPFS: "10G"
  ORD_SOUMET_M: "100G"
  ORD_SOUMET_W: "60"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - run_intel
  - run_gnu
  - package
  - deploy

before_script:
  - source ~/ci-admin/env/init.sh
  - export PIPELINE_SUBDIR=${ECCI_BUILD_DIR}/precaution/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}

#----- rhel-9-graniterapids-64-intel-2025.1.0
# U3 Intel 2025 with installed RPN-SI libs
build:rhel-9-graniterapids-64-intel-2025.1.0:
  variables:
     ORD_SOUMET_MACH: ppp6t
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . r.env.dot --carch graniterapids
    - . ./.eccc_setup_intel_2025.1.0
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-9-graniterapids-64-intel-2025.1.0
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-9-graniterapids-64-intel-2025.1.0
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-9-graniterapids-64-intel-2025.1.0 .
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-9-graniterapids-64-intel-2025.1.0
    - cmake -DTARGET_PROC=graniterapids ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-9-graniterapids-64-intel-2025.1.0

package:rhel-9-graniterapids-64-intel-2025.1.0:
   variables:
      ORD_SOUMET_MACH: ppp6t
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - /^dev_6\.[0-9]*$/
      - schedules
   dependencies:
      - build:rhel-9-graniterapids-64-intel-2025.1.0
   script:
      - set +e
      - . r.env.dot --carch graniterapids
      - . ./.eccc_setup_intel_2025.1.0
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-rhel-9-graniterapids-64-intel-2025.1.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-amd64_gnu-9.3.0
build:rhel-8-amd64_gnu-9.3.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-9.3.0
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-9.3.0
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-amd64-64-gnu-9.3.0 .
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-9.3.0
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-amd64-64-gnu-9.3.0
    - sps_dbase

#----- rhel-8-amd64_gnu-14.2.0
build:rhel-8-amd64_gnu-14.2.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ./.eccc_setup_gnu_14
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-14.2.0
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-amd64-64-gnu-14.2.0
    - cmake ${SRC_DIR}
    - time make -j $NCPUS
  allow_failure: true

#----- rhel-8-icelake-64-intel-2022.1.2 with sources
# U2 Intel 2022 with RPN-SI sources
build:intel-with-sources-rhel-8-icelake-64-intel-2022.1.2:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ./.eccc_setup_intel_2022.1.2
    - set -e
    - export WITH_SYSTEM_RPN=FALSE
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2-with-sources
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2-with-sources
    - cmake -DWITH_SYSTEM_RPN=FALSE ${SRC_DIR}
    - time make -j $NCPUS
  allow_failure: true

#----- rhel-8-icelake-64-intel-2025.1.0
# U2 Intel 2025 with installed RPN-SI libs
# Used for testing configs and for SSM package
build:rhel-8-icelake-64-intel-2025.1.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2025.1.0
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2025.1.0
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2025.1.0 .
    - ./scripts/link-dbase.sh
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2025.1.0
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-icelake-64-intel-2025.1.0

package:rhel-8-icelake-64-intel-2025.1.0:
   variables:
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - /^dev_6\.[0-9]$/
      - schedules
   dependencies:
      - build:rhel-8-icelake-64-intel-2025.1.0
   script:
      - set +e
      - . ./.eccc_setup_intel_2025.1.0
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2025.1.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-icelake-64-intel-2022.1.2
# U2 Intel 2022 with installed RPN-SI libs
build:rhel-8-icelake-64-intel-2022.1.2:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
    - concurrent
  when: always
  script:
    - set +e
    - . ./.eccc_setup_intel_2022.1.2
    - set -e
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - mkdir -pv ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2
    - ln -sf ${PIPELINE_SUBDIR}/work-rhel-8-icelake-64-intel-2022.1.2 .
    - SRC_DIR=$(pwd)
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS
    - time make work
  artifacts:
    expire_in: 4 hrs
    paths:
    - work-rhel-8-icelake-64-intel-2022.1.2
    - sps_dbase

package:rhel-8-icelake-64-intel-2022.1.2:
   variables:
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - /^dev_6\.[0-9]$/
      - schedules
   needs:
      - build:rhel-8-icelake-64-intel-2022.1.2
   script:
      - set +e
      - . ./.eccc_setup_intel_2022.1.2
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2022.1.2
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- rhel-8-icelake-64-intel-2021.4.0
# U2 Intel 2021 with installed RPN-SI libs
# Used for SSM package
build:rhel-8-icelake-64-intel-2021.4.0:
  variables:
     ORD_SOUMET_CPUS: "4"
     ORD_SOUMET_W: "30"
     ORD_SOUMET_M: "8G"
     ORD_SOUMET_TMPFS: "1G"
  stage: build
  tags:
  - concurrent
  only:
  - tags
  - /^dev_6\.[0-9]$/
  - schedules
  when: always
  script:
    - set +e
    - . ./.eccc_setup_intel_2021.4.0
    - set -e
    - SRC_DIR=$(pwd)
    - mkdir -pv ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
    - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
    - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
    - time make -j $NCPUS

package:rhel-8-icelake-64-intel-2021.4.0:
   variables:
      ORD_SOUMET_CPUS: "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - tags
      - /^dev_6\.[0-9]$/
      - schedules
   needs:
      - build:rhel-8-icelake-64-intel-2021.4.0
   script:
      - set +e
      - . ./.eccc_setup_intel_2021.4.0
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-rhel-8-icelake-64-intel-2021.4.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}

#----- ubuntu-24.04-amd64_intel-2025.1.0
build:ubuntu-24.04-amd64-intel-2025.1.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu24.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - /^dev_6\.[0-9]$/
     - tags
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2025.1.0
      - set -e
      - export EC_ARCH=ubuntu-24.04-amd-64/inteloneapi-2025.1.0
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-24.04-amd64-intel-2025.1.0
      - SRC_DIR=$(pwd)
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-24.04-amd64-intel-2025.1.0
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS
      - time make work
   allow_failure: true

package:ubuntu-24.04-amd64-intel-2025.1.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu24.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - /^dev_6\.[0-9]$/
      - tags
      - schedules
   dependencies:
      - build:ubuntu-24.04-amd64-intel-2025.1.0
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2025.1.0
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-24.04-amd64-intel-2025.1.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}
   allow_failure: true

#----- ubuntu-22.04-amd64_intel-2022.1.2
build:ubuntu-22.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - /^dev_6\.[0-9]$/
     - tags
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2022.1.2
      - set -e
      - SRC_DIR=$(pwd)
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS
   allow_failure: true

package:ubuntu-22.04-amd64-intel-2022.1.2:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - /^dev_6\.[0-9]$/
      - tags
      - schedules
   needs:
      - build:ubuntu-22.04-amd64-intel-2022.1.2
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2022.1.2
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2022.1.2
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}
   allow_failure: true

#----- ubuntu-22.04-amd64_intel-2023.2.0
build:ubuntu-22.04-amd64-intel-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS: "4"
      ORD_SOUMET_W: "30"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: build
   tags:
     - concurrent
   only:
     - /^dev_6\.[0-9]$/
     - tags
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2023.2.0
      - set -e
      - SRC_DIR=$(pwd)
      - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2023.2.0
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2023.2.0
      - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
      - time make -j $NCPUS
   allow_failure: true

package:ubuntu-22.04-amd64-intel-2023.2.0:
   variables:
      ORD_SOUMET_MACH    : gpsc7
      ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
      ORD_SOUMET_PROJECT : eccc_mrd
      ORD_SOUMET_CPUS    : "2"
      ORD_SOUMET_W: "10"
      ORD_SOUMET_M: "8G"
      ORD_SOUMET_TMPFS: "1G"
   stage: package
   tags:
      - concurrent
   only:
      - /^dev_6\.[0-9]$/
      - tags
      - schedules
   needs:
      - build:ubuntu-22.04-amd64-intel-2023.2.0
   script:
      - set +e
      - . r.env.dot --arch amd64
      - . ./.eccc_setup_intel_2023.2.0
      - set -e
      - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-intel-2023.2.0
      - make package
      - ~/ci-admin/bin/ci-package-ssm.sh package ${ECCI_PROCESS}
   allow_failure: true

#----- ubuntu-22.04-amd64_gnu-11.4.0
# build:ubuntu-22.04-amd64-gnu-11.4.0:
#    variables:
#       ORD_SOUMET_MACH    : gpsc7
#       ORD_SOUMET_IMAGE   : registry.maze.science.gc.ca/ssc-hpcs/generic-job:ubuntu22.04
#       ORD_SOUMET_PROJECT : eccc_mrd
#       ORD_SOUMET_CPUS    : "2"
#       ORD_SOUMET_W: "10"
#       ORD_SOUMET_M: "8G"
#       ORD_SOUMET_TMPFS: "1G"
#    stage: build
#    tags:
#      - concurrent
#    only:
#      - /^dev_6\.[0-9]$/
#      - tags
#    script:
#       - set +e
#       - . r.env.dot --arch amd64
#       - . ./.eccc_setup_gnu
#       - set -e
#       - SRC_DIR=$(pwd)
#       - mkdir -pv ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-gnu-11.4.0
#       - cd ${PIPELINE_SUBDIR}/build-ubuntu-22.04-amd64-64-gnu-11.4.0
#       - cmake -DWITH_SYSTEM_RPN=TRUE ${SRC_DIR}
#       - time make -j $NCPUS
#   allow_failure: true

deploy:staging:
   stage: deploy
   tags:
      - U2
   only:
      - tags
      - /^dev_6\.[0-9]$/
      - schedules
   script:
      - ~/ci-admin/bin/ci-stage-ssm.sh sps sps "${CI_COMMIT_TAG}" "${ECCI_PROCESS}"

#----- Running test configurations for rhel-8-icelake-64-intel-2025.1.0
caldas_hrdps_isba_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/caldas_hrdps_isba --ptopo=6x1 --btopo=1x1 --inorder

CSLM_cfgs_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/CSLM_cfgs --ptopo=8x10 --btopo=1x1 --inorder

SPS_cfgs_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SPS_cfgs --ptopo 2x2x1 --btopo=1x1 --inorder

SPS_isba_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e 
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg configurations/SPS_isba_cfgs --ptopo=2x2x1 --btopo=1x1 --inorder

tape1_grid_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/tape1_grid --ptopo=1x1x1 --btopo=1x1 --inorder

TEB_national_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/TEB_national --ptopo=8x10 --btopo=1x1 --inorder

SVS2_cfgs_intel:
  stage: run_intel
  needs:
  - build:rhel-8-icelake-64-intel-2025.1.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_intel_2025.1.0
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - set -e
    - ./scripts/link-dbase.sh
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SVS2_cfgs --ptopo=6x6 --btopo=1x1 --inorder

#----- Running test configurations for rhel-8-amd64_gnu-9.3.0
caldas_hrdps_isba_gnu:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/caldas_hrdps_isba --ptopo=6x1 --btopo=1x1 --inorder

CSLM_cfgs_gnu:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/CSLM_cfgs --ptopo=8x10 --btopo=1x1 --inorder

SPS_cfgs_gnu_9.3.0:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SPS_cfgs --ptopo 2x2x1 --btopo=1x1 --inorder

SPS_isba_gnu_9.3.0:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg configurations/SPS_isba_cfgs --ptopo=2x2x1 --btopo=1x1 --inorder

tape1_grid_gnu:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/tape1_grid --ptopo=1x1x1 --btopo=1x1 --inorder

TEB_national_gnu:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/TEB_national --ptopo=8x10 --btopo=1x1 --inorder

SVS2_cfgs_gnu:
  stage: run_gnu
  needs:
  - build:rhel-8-amd64_gnu-9.3.0
  when: always
  allow_failure: true
  script:
    - set +e
    - . ./.eccc_setup_gnu
    - . ssmuse-sh -d /fs/ssm/eccc/cmo/isst/maestro/20230316
    - ./scripts/link-dbase.sh
    - set -e
    - cd $SPS_WORK
    - sps.sh --dircfg ./configurations/SVS2_cfgs --ptopo=6x6 --btopo=1x1 --inorder
